"""empty message

Revision ID: 6250ae4ff4e0
Revises: f463841c7894
Create Date: 2021-10-27 12:24:32.279099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6250ae4ff4e0'
down_revision = 'f463841c7894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('podcasts', sa.Column('author', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('podcasts', 'author')
    # ### end Alembic commands ###
