"""empty message

Revision ID: f60b5499d865
Revises: 6250ae4ff4e0
Create Date: 2021-10-27 13:00:55.555842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f60b5499d865'
down_revision = '6250ae4ff4e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episodes', sa.Column('podcast_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episodes', 'podcast_link')
    # ### end Alembic commands ###
